In [1]:
import numpy as np
import os

In [93]:
def temp_data():
    data = np.array([np.array([1,1,1,1,1]),
                    np.array([1,9,9,9,1]),
                    np.array([1,9,1,9,1]),
                    np.array([1,9,9,9,1]),
                    np.array([1,1,1,1,1])])
    data = np.stack(data)
    return data

def get_data():
        os.getcwd()
        os.chdir(r'C:\Users\justi\Github\advent_of_code\day 11')
        
        with open('train.txt') as f:
            lines = f.readlines()

        data = [x.replace('\n','') for x in lines]  # remove the '\n'
        data = [[int(x.split()[0]) for x in list] for list in data]
        data = [np.array(line) for line in data]
        data = np.array(data)
        data = np.stack(data)
        
        return data
    
# function to do DFS for a 2D matrix (considering 8 neighbors only)
def first(data, row, col):
    for i in range(row):
        for j in range(col):
            data[i,j] += 1
    
    return(data)

def second(data, i, j):
    # directions
    dirs = [(-1,-1), (-1,0), (-1,1), (0,-1), (0,1), (1,-1), (1,0), (1,1)]
    row = data.shape[0]
    col = data.shape[1]
    
    for k in range(8):
        x = i + dirs[k][0]
        y = j + dirs[k][1]
        if (x >= 0 and x < row and y >= 0 and y < col):
            data[x,y] += 1
    return data
    
def flash(data,i,j):
    count = 0
    if data[i,j] >= 9:
        data[i,j] = 0
        count += 1
    else:
        data[i,j]
    return data, count

def steps(data, row, col):
    flashes = 0
    data = first(data,row, col)
    for i in range(row):
        for j in range(col):
            if data[i,j] >= 9:
               data = second(data,i,j)
               
    for i in range(row):
        for j in range(col):
            data, count = flash(data,i,j)
            flashes += count
    return data, flashes

def main():
    flashes = 0
    data = get_data()
    row = data.shape[0]
    col = data.shape[1]
    for i in range(1):
        data, step_flashes = steps(data, row, col)
        flashes += step_flashes
        i==i
    
    print(data)
    return flashes

main()

[[7 7 0 6 3 6 4 3 3 4]
 [4 0 7 8 0 7 5 8 2 2]
 [7 4 8 6 7 7 7 2 8 4]
 [7 2 5 2 5 5 8 2 6 8]
 [7 4 6 8 5 0 7 5 0 0]
 [5 2 7 0 8 5 6 7 6 7]
 [4 4 0 0 0 8 3 8 3 2]
 [0 0 0 8 0 0 4 3 4 5]
 [7 0 0 0 0 0 0 7 6 5]
 [7 5 0 8 0 0 4 7 3 7]]


24

In [46]:
data = get_data()
for i in  range(data.shape[0]):
    for j in range(data.shape[1]):
        if data[i,j] >= 9:
            print(data)
        else:
            print('no change')

no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
no change
