In [1]:
import os

os.getcwd()
os.chdir(r'C:\Users\justi.DATA-POWER\Documents\Github\advent_of_code\day 9')

In [2]:
with open('example.txt') as f:
    lines = f.readlines()

lines = [x[:-1] for x in lines]
#print(lines)

In [3]:
import numpy as np

def split(string):
    return [item for item in string]

input = [split(x) for x in lines]
input = np.matrix(input)
input = input.astype(int)
input


matrix([[2, 1, 9, 9, 9, 4, 3, 2, 1, 0],
        [3, 9, 8, 7, 8, 9, 4, 9, 2, 1],
        [9, 8, 5, 6, 7, 8, 9, 8, 9, 2],
        [8, 7, 6, 7, 8, 9, 6, 7, 8, 9],
        [9, 8, 9, 9, 9, 6, 5, 6, 7, 8]])

In [4]:
# i = row
# x = column

def find_nines(data):
    nines = np.array(np.where(data == 9))
    nines = np.stack((nines[0], nines[1]), axis = 1)  # reshape 2 arrays into 1 array of list of points in the matrix
    return nines

def make_tracker(data):
    nines = find_nines(data)
    size = data.shape
    tracker = np.zeros(size) # score card
    for n in nines:
        tracker[n[0], n[1]] = 9
    return tracker



def submatrix(data, i, x):  # submatric creator 
    collect = None
    if i == 0 and x == 0:                       # top left corner
        result = data[np.ix_([i,i+1],[x,x+1])]  # returns 2x2 matrix
        result[1,1] = 99  # not worried about diagonals
        if result.min() == result[0,0] and result.min() < 9:
            collect = [result.min(),(i,x)] # collect the value to keep
            
    elif i ==0 and x == input.shape[1] - 1:     # top right corner
        result = data[np.ix_([i,i+1], [x-1,x])]  # returns 2x2 matrix
        result[1, 0] = 99  # not worried about diagonals
        if result.min() == result[0,1] and result.min() < 9:
            collect = [result.min(),(i,x)] # collect the value to keep
            
    elif i== input.shape[0]-1 and x == 0:       # bottom left corner
        result = data[np.ix_([i-1,i], [x,x+1])] 
        result[0,1] = 99  # not worried about diagonals
        if result.min() == result[1,0] and result.min() < 9:
            collect = [result.min(),(i,x)] # collect the value to keep
            
    elif i == input.shape[0] - 1 and x == input.shape[1] - 1: # bottom right corner
        result = data[np.ix_([i-1,i], [x-1,x])]
        result[0,0] == 99
        if result.min() == result[1,1] and result.min() < 9:
            collect = [result.min(),(i,x)]
            
    elif i == 0:                                # top row
        result = data[np.ix_([i,i+1], [x-1, x, x+1])] # returns 3x2 matrix
        result[1,0] = 99
        result[1,2] = 99
        if result.min() == result[0,1] and result.min() < 9:
            collect = [result.min(),(i,x)]
            
    elif i == input.shape[0] - 1:               # bottom row
        result = data[np.ix_([i-1,i], [x-1, x, x+1])]
        result[0,0] = 99
        result[0,2] = 99
        if result.min() == result[1,1] and result.min() < 9:
            collect = [result.min(),(i,x)]
            
    elif x == 0:                                # left edge column
        result = data[np.ix_([i-1, i, i+1], [x,x+1])]
        result[0,1] = 99
        result[2,1] = 99
        if result.min() == result[1,0] and result.min() < 9:
            collect = [result.min(),(i,x)]
    
    elif x == input.shape[1] - 1:               # right edge column
        result = data[np.ix_([i-1, i, i+1], [x-1,x])]
        result[0,0] = 99
        result[2,0] = 99
        if result.min() == result[1,1] and result.min() < 9:
            collect = [result.min(),(i,x)]
    
    else:                                       # everything else that is not on an edge or in a corner
        result = data[np.ix_([i-1, i, i+1], [x-1, x, x+1])] # returns 3x3 matrix
        result[0,0] = 99
        result[2,0] = 99
        result[0,2] = 99
        result[2,2] = 99
        if result.min() == result[1,1] and result.min() < 9:
            collect = [result.min(),(i,x)]
    
    return collect

def add_collect(input):
    lowest_list = []
    
    for i in range(input.shape[0]):
        for x in range(input.shape[1]):
            lowest = submatrix(input, i,x)
            if lowest != None:
                lowest_list.append(lowest)
    
    low = [x[0] for x in lowest_list]  # the lowest number
    idx = np.array([x[1] for x in lowest_list])  # index of the lowest number in the overall matrix

    risk_level = [x+1 for x in low]    # calculate the risk level
    return sum(risk_level), low, idx





In [45]:



risk, low, low_idx = add_collect(input)


### <font color='green'>--- Part Two ---</font>

In [77]:
nines_loc = find_nines(input)
tracker = make_tracker(input)

# organize the nines by row
nines = []
for s in range(input.shape[0]):
    nines.append([x for i,x in enumerate(nines_loc) if nines_loc[i][0] == s])

idx = []
for s in range(input.shape[0]):
    idx.append([x for i,x in enumerate(low_idx) if low_idx[i][0] == s])
idx = [[[p,0]] if x == [] else x for p,x in enumerate(idx)]

nines, idx

([[array([0, 2], dtype=int64),
   array([0, 3], dtype=int64),
   array([0, 4], dtype=int64)],
  [array([1, 1], dtype=int64),
   array([1, 5], dtype=int64),
   array([1, 7], dtype=int64)],
  [array([2, 0], dtype=int64),
   array([2, 6], dtype=int64),
   array([2, 8], dtype=int64)],
  [array([3, 5], dtype=int64), array([3, 9], dtype=int64)],
  [array([4, 0], dtype=int64),
   array([4, 2], dtype=int64),
   array([4, 3], dtype=int64),
   array([4, 4], dtype=int64)]],
 [[array([0, 1]), array([0, 9])],
  [[1, 0]],
  [array([2, 2])],
  [[3, 0]],
  [array([4, 6])]])

In [78]:
from scipy.spatial import distance_matrix


In [79]:
# compute how far each nine is from the left edge of the matrix

nine_dist = [distance_matrix([[d,0]], l) for d,l in enumerate(nines)]
nine_dist

[array([[2., 3., 4.]]),
 array([[1., 5., 7.]]),
 array([[0., 6., 8.]]),
 array([[5., 9.]]),
 array([[0., 2., 3., 4.]])]

In [80]:
idx_dist = [distance_matrix([[d,0]], l) for d,l in enumerate(idx)]
idx_dist

[array([[1., 9.]]), array([[0.]]), array([[2.]]), array([[0.]]), array([[6.]])]