In [141]:
# Advent Puzzle Day 3
import numpy as np
import os

In [142]:
os.chdir('/Users/justinehly/GitHub/advent_of_code/day 4/')
os.getcwd()

'/Users/justinehly/GitHub/advent_of_code/day 4'

In [143]:
input = 'day_4_input.txt'
with open(input) as f:
    lines = f.readlines()

In [144]:
DRAW = [lines[0][:-1]]
DRAW = DRAW[0].split(',')

In [145]:

boards = lines[1:]
boards = [i[:-1] for i in boards if i != '\n']
squid = []
for i,x in enumerate(boards):
    squid.append(x.split())
BINGO = []
b = 0
for i in range(0, len(squid), 5):
    BINGO.append(squid[i:i+5])



In [146]:
BINGO

[[['57', '7', '8', '38', '31'],
  ['17', '96', '5', '12', '18'],
  ['58', '45', '81', '89', '4'],
  ['73', '51', '93', '32', '10'],
  ['74', '50', '26', '0', '24']],
 [['79', '67', '21', '84', '71'],
  ['25', '22', '19', '80', '13'],
  ['10', '63', '90', '78', '33'],
  ['93', '50', '89', '58', '87'],
  ['91', '7', '45', '6', '41']],
 [['66', '85', '4', '91', '41'],
  ['59', '69', '16', '0', '90'],
  ['35', '13', '64', '61', '93'],
  ['11', '20', '29', '67', '77'],
  ['92', '75', '58', '3', '34']],
 [['19', '1', '34', '50', '76'],
  ['26', '75', '8', '28', '20'],
  ['96', '64', '49', '77', '2'],
  ['18', '58', '62', '53', '60'],
  ['82', '99', '38', '10', '83']],
 [['89', '69', '97', '16', '48'],
  ['32', '3', '83', '17', '33'],
  ['82', '53', '15', '50', '94'],
  ['52', '0', '86', '25', '81'],
  ['42', '38', '84', '73', '76']],
 [['68', '18', '44', '61', '66'],
  ['24', '21', '22', '6', '41'],
  ['48', '29', '4', '64', '78'],
  ['93', '25', '88', '95', '96'],
  ['72', '49', '51', '2', 

In [154]:
BINGO2 = [np.zeros((5,5)) for i in range(100)]
BINGO2

[array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]